# Gift Database #

# stores the gift database entries for the mod's new gifts overhaul system
# backported from IA2, but modified for IA1
# includes all gifts from IA2

init 100 python:
    def mod_gift_database_entries():
        return [
            {
                "id": "5_in_1_board_game_set",
                "name": "5 in 1 Board Game Set",
                "description": "Ten classic board games contained in a box with their own interchangeable playing surface.",
                "price": 25,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "beach_blanket",
                "name": "Beach Blanket",
                "description": "Quick drying nylon blanket to use when going to the beach or when having a picnic.",
                "price": 30,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "bouncy_ball",
                "name": "Bouncy Ball",
                "description": "A bouncy toy with a spherical shape. Throw it hard for maximum bouncing!",
                "price": 100,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "box_of_chocolates",
                "name": "Box of Chocolates",
                "description": "A delicious arrangement of milk, vanilla, and dark type chocolates with creamy filling in the center.",
                "price": 15,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "cuddle_whamples_teddy_bear",
                "name": "Cuddle Whamples Teddy Bear",
                "description": "Cuddle Wumples outfitted in battle equipment for some reason. Don't worry, the armor is still plush and cuddly!",
                "price": 100,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "cuddle_wumples_teddy_bear",
                "name": "Cuddle Wumples Teddy Bear",
                "description": "A cute teddy bear for snuggling or collecting.",
                "price": 100,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "dumbell_set",
                "name": "Dumbell Set",
                "description": "Set of dumbells with three different weight settings to help build and strengthen muscle.",
                "price": 50,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "e-book_reader",
                "name": "E-Book Reader",
                "description": "Anti-glare handheld tablet that gives access to hundreds of ready to read digital books.",
                "price": 50,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "fornimate_capsule",
                "name": "Fornimate Capsule",
                "description": "A small mystery capsule containing a random Fornimate figurine.",
                "price": 100,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "hair_comb_pack",
                "name": "Hair Brush Pack",
                "description": "Set of hairbrushes for managing large amounts of hair with ease.",
                "price": 20,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "headphones",
                "name": "Headphones",
                "description": "High fidelity noise canceling headphones with cushioned ear pieces to listen in private.",
                "price": 40,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "hero_plush",
                "name": "Hero Plush",
                "description": "A plush of an adventurous young blond man. Oddly very popular with girls and is often paired with the wolf girl plush.",
                "price": 100,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "hot_sauce_gift_set",
                "name": "Hot Sauce Gift Set",
                "description": "A collection of hot sauces ranging from mild to extreme heat. For the spice and food lover.",
                "price": 30,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "jitter_whirler",
                "name": "Jitter Whirler",
                "description": "A toy that just spins in place with minimal effort. Popular on social media.",
                "price": 100,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "kira_plush",
                "name": "Kira Plush",
                "description": "A plush of an athletic woman with big breasts. Features an iconic big grin on her face.",
                "price": 100,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "laser_light_projector",
                "name": "Laser Light Projector",
                "description": "Projects colorful patterns on the walls and ceilings of a room with the press of a button.",
                "price": 25,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "laser_tag_guns",
                "name": "Laser Tag Guns",
                "description": "Pair of laser tag guns for indoor and outdoor laser battles.",
                "price": 40,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "lipstick",
                "name": "Lipstick",
                "description": "A crimson red lipstick in a compact case. Ideal for the sophisticated working woman.",
                "price": 20,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "makeup_kit",
                "name": "Makeup Kit",
                "description": "A portable make-up kit, perfect for someone who likes to maintain their looks throughout the day.",
                "price": 25,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "moisturizer_cream",
                "name": "Moisturizer Cream",
                "description": "Moisturizing cream that helps prevent dry, cracked skin such as on the hands, arms, and face.",
                "price": 10,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "motivational_poster",
                "name": "Motivational Poster",
                "description": "Poster with a image of a picturesque landscape along with an inpiring quote.",
                "price": 10,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "movego_action_camera",
                "name": "MoveGo Action Camera",
                "description": "Latest model of the best selling action camera on the market. Perfect for capturing fast moving activities and attaching to a selfie stick.",
                "price": 75,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "movie_gift_card",
                "name": "Movie Gift Card",
                "description": "Gift card that can be used at the movie theater or to rent or purchase movies at home.",
                "price": 25,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "nate_plush",
                "name": "Nate Plush",
                "description": "A plush of a boy with brown hair. For some reason,  this plush is really popular with girls.",
                "price": 100,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "neon_yo-yo",
                "name": "Neon Yo-yo",
                "description": "A bright green colored yo-yo that glows in the dark.",
                "price": 100,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "pajamas",
                "name": "Pajamas",
                "description": "Comfy pajamas that keep you warm and cozy on cold days.",
                "price": 30,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "pirate_ship_model_kit",
                "name": "Pirate Ship Model Kit",
                "description": "Challenging model kit of a complete pirate ship with over three hundred separate pieces.",
                "price": 40,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "premium_motorcycle_helmet",
                "name": "Premium Motorcycle Helmet",
                "description": "A high quality helmet with a polished finish and double insulation for extra comfort when riding for long periods.",
                "price": 100,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "reflexviz.tv_emoji_stickers",
                "name": "ReflexViz.TV Emoji Stickers",
                "description": "A collection of emoji stickers frequently used on the streaming platform ReflexViz.TV.",
                "price": 100,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "restaurant_gift_card",
                "name": "Restaurant Gift Card",
                "description": "Gift card that can be used at restaurants and dining establishments.",
                "price": 25,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "sam_plush",
                "name": "Sam Plush",
                "description": "A plush of a girl with blonde hair wearing a hat that says \"Twin Sticks.\" Appears to be a pretty popular streamer.",
                "price": 100,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "seat_cushion_massager",
                "name": "Seat Cushion Massager",
                "description": "Powerful electric massager that automatically massages your upper and lower back when sitting on a chair.",
                "price": 50,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "sleep_mask",
                "name": "Sleep Mask",
                "description": "Plush mask to wear over your eyes to help you fall asleep more easily at night.",
                "price": 20,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "smartphone_case",
                "name": "Smartphone Case",
                "description": "A sturdy and durable case to protect the most high end smartphones.",
                "price": 25,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "sneakers",
                "name": "Sneakers",
                "description": "Durable and flexible shoes that can be comfortably worn for hours during the work day or through demanding activities.",
                "price": 35,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "sunglasses",
                "name": "Sunglasses",
                "description": "Stylish sunglasses to keep your eyes protected on bright, sunny days.",
                "price": 20,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "thermos",
                "name": "Thermos",
                "description": "Keep your beverage hot or cold in this sleek stainless steel thermos with easy twist off cap.",
                "price": 25,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "todd_mosss_crystal_collection",
                "name": "Todd Moss's Crystal Collection",
                "description": "As seen on TV! Colorful arrangement of Todd Moss's favorite crystals including quartz, emerald, amethyst and more.",
                "price": 30,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "toolset",
                "name": "Toolset",
                "description": "An assortment of useful tools. For the tinkerer and do it yourself person in your life.",
                "price": 30,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "training_gloves",
                "name": "Training Gloves",
                "description": "Fingerless, impact absorbing gloves for sparring and punching bag workouts.",
                "price": 40,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "vicky_plush",
                "name": "Vicky Plush",
                "description": "A plush of a busty business woman. Despite being easily obtainable, people often ask online about how to get her.",
                "price": 100,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "wireless_earbuds",
                "name": "Wireless Earbuds",
                "description": "Earbuds with long lasting battery life and universal in ear fit that won't fall out.",
                "price": 40,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "wolf_girl_plush",
                "name": "Wolf Girl Plush",
                "description": "A plush of an wolf girl with a scar across one eye and wearing heavy armor. Despite her warrior appearance, she looks super fluffy and huggable.",
                "price": 100,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
            {
                "id": "wool_slippers",
                "name": "Wool Slippers",
                "description": "Soft and warm slippers to keep your feet warm from cold floors.",
                "price": 25,
                "disable_after_first_buy": "False",
                "disappear_after_first_buy": "False",
                "condition_visible": "True",
                "condition_enabled": "True",
                "limit": 0,
                "label_on_buy": "",
                "action_on_buy": "",
                "tags": "[\"gift\"]",
                "null": ""
            },
        ]

