############################################
#### Modders, do NOT edit this file! #######
#### Edit "mod_register.rpy" instead! ######
############################################

init -99 python:
    mod_registry = []
    mod_help_texts = {}
    help_modal_open = False # prevents all (?) lighting up

# Updates the navigation screen first to show "Mods"
init 200:
    screen navigation():

        vbox:
            style_prefix "navigation"

            xpos gui.navigation_xpos
            yalign 0.5

            spacing gui.navigation_spacing

            if main_menu:

                textbutton _("Start") action Start()

            else:

                textbutton _("History") action ShowMenu("history")

                textbutton _("Save") action  If(store.disable_saves, None, ShowMenu("save"))

            if not wholesome_mode:
                textbutton _("Load") action ShowMenu("load")

            # unused
            if False and not main_menu:
                if display_new_game_plus_option:
                    textbutton _("New Game+") action Confirm("New Game+ allows you to start a new game while retaining rewards from minigames. Any other progress will not be carried over. Are you sure you want to do this?", Jump("new_game_plus_label"))

            textbutton _("Preferences") action ShowMenu("preferences")

            # Show Mods button
            textbutton _("Mods") action ShowMenu("mods_preferences")

            if _in_replay:

                textbutton _("End Replay") action EndReplay(confirm=True)

            elif not main_menu:

                textbutton _("Main Menu") action MainMenu()

            textbutton _("About") action ShowMenu("about")

            if renpy.variant("pc"):

                ## Help isn't necessary or relevant to mobile devices.
                textbutton _("Help") action ShowMenu("help")

                ## The quit button is banned on iOS and unnecessary on Android.
                textbutton _("Quit") action Quit(confirm=not main_menu)

# Removes any traces of "Mods" from the Preferences menu
# Mainly for mods like Supersexual Awakening that still use this function
# Contradicts with the "Mods" button added to the navigation screen, so it's been gutted
init 100:
    screen preferences():

        tag menu

        if renpy.mobile:
            $ cols = 2
        else:
            $ cols = 4

        if not wholesome_mode:
            use game_menu(_("Preferences"), scroll="viewport"):

                vbox:

                    hbox:
                        spacing 50
                        box_wrap True

                        if renpy.variant("pc"):

                            vbox:
                                style_prefix "radio"
                                label _("Display")
                                textbutton _("Window") action Preference("display", "window")
                                textbutton _("Fullscreen") action Preference("display", "fullscreen")

                        vbox:
                            style_prefix "radio"
                            label _("Rollback Side")
                            textbutton _("Disable") action Preference("rollback side", "disable")
                            textbutton _("Left") action Preference("rollback side", "left")
                            textbutton _("Right") action Preference("rollback side", "right")

                        vbox:
                            style_prefix "check"
                            label _("Skip")
                            textbutton _("Unseen Text") action Preference("skip", "toggle")
                            textbutton _("After Choices") action Preference("after choices", "toggle")
                            textbutton _("Transitions") action InvertSelected(Preference("transitions", "toggle"))

                        vbox:
                            style_prefix "check"
                            label _("Extra")

                            if not wholesome_mode:
                                textbutton _("Disable Splash") action ToggleField(persistent, 'disable_splash_movie', True, False)
                                textbutton _("Disable Warning") action ToggleField(persistent, 'disable_warning', True, False)
                                textbutton _("Disable Dream Music") action ToggleField(persistent, 'disable_dream_music', True, False)
                                textbutton _("Disable Dream Blur") action ToggleField(persistent, 'disable_dream_blur', True, False)
                                textbutton _("Enable Sex Sounds") action ToggleField(persistent, 'enable_sex_sounds', True, False)
                                textbutton _("Mousewheel Choice Scroll") action ToggleField(persistent, 'mouse_wheel_choice_scroll', True, False)
                                textbutton _("Use \"Incestral Awakening\" As Name") action ToggleField(persistent, 'use_incestral_awakening_name', True, False)

                                if not main_menu:
                                    textbutton _("Hide [sa.say_name] ! Notification") action ToggleField(persistent, 'hide_sam_notification', True, False)
                                    textbutton _("Hide [si.say_name] ! Notification") action ToggleField(persistent, 'hide_simone_notification', True, False)
                                    textbutton _("Hide [k.say_name] ! Notification") action ToggleField(persistent, 'hide_kira_notification', True, False)

                                    if store.had_julia_arrived_scene:
                                        textbutton _("Hide [julia.say_name] ! Notification") action ToggleField(persistent, 'hide_julia_notification', True, False)

                                    if store.had_janet_intro_scene:
                                        textbutton _("Hide [janet.say_name] ! Notification") action ToggleField(persistent, 'hide_janet_notification', True, False)

                                    if store.had_edna_intro_scene:
                                        textbutton _("Hide [edna.say_name] ! Notification") action ToggleField(persistent, 'hide_edna_notification', True, False)

                                    if store.had_vicky_intro_scene:
                                        textbutton _("Hide Vicky ! Notification") action ToggleField(persistent, 'hide_vicky_notification', True, False)

                                    if "gloryhole_handjob_scene" in store.scenes_completed:
                                        textbutton _("Hide Kacey ! Notification") action ToggleField(persistent, 'hide_kacey_notification', True, False)
                                    else:
                                        textbutton _("Hide Park ! Notification") action ToggleField(persistent, 'hide_kacey_notification', True, False)

#                                    if had_beach_intro:
#                                       textbutton _("Hide Beach ! Notification") action ToggleField(persistent, 'hide_beach_notification', True, False)

#                use mods_preferences       
#                style_prefix "check"
            
#                for mod_option in mod_options():
#                    textbutton _(mod_option[0]) action ToggleField(persistent, mod_option[1], True, False)

#                if persistent.leftovers_mod_detected:
#                    vbox:
#                        style_prefix "check"
#                        label _("Leftovers-Mod")

#                        for mod_leftovers_option in mod_leftovers_options():
#                            textbutton _(mod_leftovers_option[0]) action ToggleField(persistent, mod_leftovers_option[1], True, False)

                    hbox:
                        style_prefix "slider"
                        box_wrap True

                        vbox:

                            label _("Text Speed")

                            bar value Preference("text speed")

                            label _("Auto-Forward Time")

                            bar value Preference("auto-forward time")

                        use audio_preferences

                    if main_menu:
                        vbox:
                            label _("Daytime (Home) Music")
                            style_prefix "check"
                            use music_disable_vbox( disable_audio_filenames( home_daytime_music_list() ) )

                        vbox:
                            label _("Evening (Home) Music")
                            style_prefix "check"
                            use music_disable_vbox( disable_audio_filenames( home_evening_music_list() ) )

                        vbox:
                            label _("Daytime (Outside) Music")
                            style_prefix "check"
                            use music_disable_vbox( disable_audio_filenames( outside_daytime_music_list() ) )
                        vbox:
                            label _("Evening (Outside) Music")
                            style_prefix "check"
                            use music_disable_vbox( disable_audio_filenames( outside_evening_music_list() ) )

# Mod Preferences
screen mods_preferences():
    tag menu

    if renpy.mobile:
        $ cols = 2
    else:
        $ cols = 4

    if not wholesome_mode:
        use game_menu(_("Mods"), scroll="viewport"): # Displays "Mods" instead of "Preferences"

            vbox:
                label _("Mods")
                style_prefix "check"

                # Displays mod detection and enabled/disabled status in the Mods menu
                # Uses the same variables as the mod registry
                $ mod_variable_map = {
                    "Smol Tits Mod": "oimon_mod_enabled",
                    "Skip Minigames": "skip_minigames_enabled",
                }

                for mod_name, detect_flag, enable_flag in mod_registry:
                    $ detected = getattr(persistent, detect_flag, False)
                    $ color = "#0c0" if detected else "#c00"

                    if detected:
                        $ status_text = "is detected"
                    else:
                        $ status_text = "is not detected"

                    if enable_flag and detected:
                        $ enabled = getattr(persistent, enable_flag, False)

                        if enabled:
                            $ status_text += " and enabled"
                        else:
                            $ status_text += " and disabled"

                    elif mod_name in mod_variable_map and detected:
                        $ enabled = getattr(persistent, mod_variable_map[mod_name], False)

                        if enabled:
                            $ status_text += " and enabled"
                        else:
                            $ status_text += " and disabled"

                    hbox:
                        spacing 10
                        xalign 0.0

                        text "{color=%s}%s %s{/color}" % (color, mod_name, status_text)

                        if mod_name in mod_help_texts:
                            textbutton "(?)":
                                style "mod_help_button"
                                xalign 0.0
                                sensitive not help_modal_open
                                action Show("mod_help_screen", mod_name=mod_name)

                vbox:
                    style_prefix "check"
                    label _("Toggle Mods")

                    for mod_option in mod_options():
                        textbutton _(mod_option[0]) action ToggleField(persistent, mod_option[1], True, False)

                if persistent.leftovers_mod_detected:
                    vbox:
                        style_prefix "check"
                        label _("Leftovers-Mod")

                        for mod_leftovers_option in mod_leftovers_options():
                            textbutton _(mod_leftovers_option[0]) action ToggleField(persistent, mod_leftovers_option[1], True, False)

                if os.path.isdir(os.path.join(renpy.config.gamedir, "mods", "supersexual_awakening")):
                    vbox:
                        style_prefix "check"
                        label _("Supersexual Awakening")

                        for mod_supersexual_option in mod_supersexual_options():
                            textbutton _(mod_supersexual_option[0]) action ToggleField(persistent, mod_supersexual_option[1], True, False)

# mod help style
style mod_help_button is text_button:
    padding (2, 4)
    size 16

# used to dim the background so the box is more prevalent
transform help_scrim_fade:
    alpha 0.0
    easein 0.25 alpha 0.90

# screen for mod info
screen mod_help_screen(mod_name):
    modal True
    zorder 200

    on "show" action SetVariable("help_modal_open", True)
    on "hide" action SetVariable("help_modal_open", False)

    add Solid("#000d") at help_scrim_fade

    frame:
        xalign 0.5
        yalign 0.5
        xsize 760
        background Frame("images/interface/ShoppingMenuBox.png", 40, 40)
        xpadding 40
        ypadding 30

        vbox:
            spacing 16

            text mod_name size 36 xalign 0.5

            $ help_text = mod_help_texts.get(mod_name, "No information available for this mod.")
            text help_text size 26 xmaximum 680

            textbutton "OK" xalign 0.5 action Hide("mod_help_screen")

label mod_help(mod_name=None):
    if mod_name is None:
        $ mod_name = persistent.current_mod_help

    call screen mod_help_screen(mod_name)

    return

########################################################################################