# Currently only houses the multi-race intro

label minigame_racing_multi_first_time_intro:
    call process_conversation_beginning([ (n, ""), (k, "pose handhip") ])

    call process_character(k, appearance = "pose handhip face neutral", text = "I've been thinking about the running track some more.")
    call process_character(k, appearance = "pose armcross face neutral", text = "Racing one person is good and all.")
    call process_character(k, appearance = "pose armcross face neutral", text = "But that only tests one thing.")
    call process_character(n, appearance = "pose handpocket face curious", text = "One thing?")
    call process_character(k, appearance = "pose handhip face neutral", text = "Speed, obviously.")
    call process_character(k, appearance = "pose handhip face neutral", text = "Like, sure you can keep up with one other person.")
    call process_character(k, appearance = "pose armsup face neutral", text = "You You pass them, hold your pace.")
    call process_character(k, appearance = "pose armcross face neutral", text = "That's all useful.")
    call process_character(k, appearance = "pose armcross face neutral", text = "But it gets a lot more interesting when there are more people involved.")
    call process_character(n, appearance = "pose behindhead face curious", text = "More people?")
    call process_character(k, appearance = "pose handhip face happy", text = "Yep.")
    call process_character(k, appearance = "pose handhip face neutral", text = "If you've got a bunch of racers around you, now you've gotta think about more than just who's fastest.")
    call process_character(k, appearance = "pose armcross face neutral", text = "You have to watch your spacing.")
    call process_character(k, appearance = "pose armcross face neutral", text = "You have to keep your rhythm.")
    call process_character(k, appearance = "pose armcross face neutral", text = "You have to deal with other people pushing the pace.")
    call process_character(k, appearance = "pose armsup face happy", text = "And most importantly...")
    call process_character(k, appearance = "pose armsup face happy", text = "You can't just stare at one person's back the whole time and zone out.")
    call process_character(n, appearance = "pose handpocket face embarrassed", text = "I wasn't doing that.")
    call process_character(k, appearance = "pose armcross face happy", text = "Sure you weren't, bro.")
    call process_character(k, appearance = "pose armcross face neutral", text = "Point is, a crowded race changes things.")
    call process_character(k, appearance = "pose handhip face neutral", text = "It's messier.")
    call process_character(k, appearance = "pose handhip face neutral", text = "Harder to read.")
    call process_character(k, appearance = "pose handhip face happy", text = "More fun too.")
    call process_character(n, appearance = "pose handpocket face curious", text = "So what, you'd race me and a bunch of other girls at the same time?")
    call process_character(k, appearance = "pose armcross face neutral", text = "If I feel like mixing things up, yeah.")
    call process_character(k, appearance = "pose armcross face neutral", text = "Doesn't always have to be the normal one-on-one race.")
    call process_character(k, appearance = "pose handhip face neutral", text = "Sometimes I just wanna see how you do when the track feels a little more crowded.")
    call process_character(n, appearance = "pose handpocket face concerned", text = "Wouldn't that be way harder?")
    call process_character(k, appearance = "pose armsup face neutral", text = "Probably.")
    call process_character(k, appearance = "pose armsup face happy", text = "That's part of the appeal.")
    call process_character(k, appearance = "pose armcross face neutral", text = "Anybody can say they put up a good time when it's just one other racer.")
    call process_character(k, appearance = "pose armcross face neutral", text = "I wanna see how you handle pressure.")
    call process_character(k, appearance = "pose handhip face neutral", text = "Can you keep up when more than one person is moving around you.")
    call process_character(k, appearance = "pose handhip face neutral", text = "Can you stay focused.")
    call process_character(k, appearance = "pose handhip face neutral", text = "Can you make good decisions without panicking.")
    call process_character(n, appearance = "pose behindhead face concerned", text = "That sounds like a lot to worry about while running.")
    call process_character(k, appearance = "pose armcross face happy", text = "Exactly.")
    call process_character(k, appearance = "pose armcross face happy", text = "Now you're getting it.")
    call process_character(n, appearance = "pose handpocket face curious", text = "So this is like the advanced version?")
    call process_character(k, appearance = "pose handhip face neutral", text = "I wouldn't call it advanced.")
    call process_character(k, appearance = "pose handhip face neutral", text = "Just different.")
    call process_character(k, appearance = "pose armcross face neutral", text = "A normal race is still the best way to see who's faster between two people.")
    call process_character(k, appearance = "pose armcross face neutral", text = "This kind of race is more about how well you handle the chaos around you.")
    call process_character(n, appearance = "pose handpocket face curious", text = "Chaos?")
    call process_character(k, appearance = "pose armsup face happy", text = "You know what I mean.")
    call process_character(k, appearance = "pose armsup face happy", text = "Keeping up with one racer is easy.")
    call process_character(k, appearance = "pose armcross face happy", text = "Keeping your cool when a whole group is moving with you is a different story.")
    call process_character(n, appearance = "pose handpocket face neutral", text = "I guess that makes sense.")
    call process_character(k, appearance = "pose handhip face neutral", text = "So here's how it'll work.")
    call process_character(k, appearance = "pose handhip face neutral", text = "If you want the normal race, we do the normal race.")
    call process_character(k, appearance = "pose armcross face neutral", text = "Simple.")
    call process_character(k, appearance = "pose armcross face neutral", text = "Just you and one other person.")
    call process_character(k, appearance = "pose armsup face neutral", text = "If you want to make things more interesting, we bring in some extra racers.")
    call process_character(n, appearance = "pose behindhead face curious", text = "And that's just for fun?")
    call process_character(k, appearance = "pose handhip face neutral", text = "Mostly, yeah.")
    call process_character(k, appearance = "pose handhip face neutral", text = "Think of it like a variation.")
    call process_character(k, appearance = "pose armcross face neutral", text = "A different kind of challenge.")
    call process_character(k, appearance = "pose armcross face happy", text = "A chance to see what you do when the track gets busy.")
    call process_character(n, appearance = "pose handpocket face concerned", text = "What if I get smoked by everybody?")
    call process_character(k, appearance = "pose armsup face happy", text = "Then you get smoked by everybody.")
    call process_character(k, appearance = "pose armsup face happy", text = "Not the end of the world.")
    call process_character(k, appearance = "pose armcross face neutral", text = "Losing tells you something too.")
    call process_character(k, appearance = "pose handhip face neutral", text = "Means you've got more work to do.")
    call process_character(n, appearance = "pose behindhead face neutral", text = "Easy for you to say.")
    call process_character(k, appearance = "pose armcross face happy", text = "You're right.")
    call process_character(k, appearance = "pose armcross face happy", text = "I say it because I'm the one who plans on winning.")
    call process_character(n, appearance = "pose handpocket face embarrassed", text = "...")
    call process_character(k, appearance = "pose handhip face neutral", text = "But hey, don't overthink it.")
    call process_character(k, appearance = "pose handhip face neutral", text = "This isn't me trying to throw you into some impossible challenge.")
    call process_character(k, appearance = "pose armcross face neutral", text = "It's just another way to race.")
    call process_character(k, appearance = "pose armcross face neutral", text = "Sometimes you keep it clean and simple.")
    call process_character(k, appearance = "pose armsup face neutral", text = "Sometimes you stir things up and see what happens.")
    call process_character(n, appearance = "pose handpocket face curious", text = "So when I ask you to race...")
    call process_character(k, appearance = "pose handhip face neutral", text = "You'll get to choose.")
    call process_character(k, appearance = "pose handhip face neutral", text = "Normal race if you want to keep it straightforward.")
    call process_character(k, appearance = "pose armsup face happy", text = "Or bring some others along if you want things to get more lively.")
    call process_character(n, appearance = "pose behindhead face neutral", text = "That actually sounds kinda fun.")
    call process_character(k, appearance = "pose armcross face happy", text = "Thought so.")
    call process_character(k, appearance = "pose armcross face happy", text = "Now all you've gotta do is decide how much punishment you feel like taking.")
    call process_character(n, appearance = "pose handpocket face concerned", text = "Punishment?")
    call process_character(k, appearance = "pose handhip face happy", text = "Relax.")
    call process_character(k, appearance = "pose handhip face happy", text = "I said {i}feel like{/i}.")
    call process_character(k, appearance = "pose armsup face happy", text = "Maybe you'll surprise me.")

    call process_end_of_conversation("minigame_racing_multi_first_time_intro", k, priority = False, considered_scene = True, override_scene_limit = True)

    return